name: Build Labels Mod

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: Android32
            os: ubuntu-latest
          - target: Android64
            os: ubuntu-latest
          - target: Win64
            os: windows-latest
          - target: MacOS
            os: macos-latest

    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build mod
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: v5.7.1
          target: ${{ matrix.target }}
          build-config: Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Labels-${{ matrix.target }}
          path: build/**/*.geode
